##
## System configuration and machine- or installation-specific macros
##

## Determine OS kernel (Linux or Darwin)
UNAME_S ?= $(shell uname -s)

## Host detection and machine defaults are conventional, tracked fragments.
## Compiler-family flags remain in this file.
include $(ROOT_DIR)/make/machines.mk

## Get PE_ENV from LMOD if being used
ifndef PE_ENV
  ifdef LMOD_FAMILY_COMPILER
      PE_ENV = $(shell echo $${LMOD_FAMILY_COMPILER} | tr a-z A-Z)
      ifeq ($(PE_ENV),GCC)
          PE_ENV = GNU
      endif
  endif
endif

#-------------------------------------------------------------------------------
# Define compiler specific variables
#-------------------------------------------------------------------------------

ifeq ($(PE_ENV),INTEL)

    ifneq ($(FC),ftn)
        FC      = ifort
        LDR     = ifort

        ARCHOPT = -xHost
    endif
    INLINE        = -ipo

    # generic flags
    OPT_FLAGS     = -g -Ofast $(ARCHOPT) $(INLINE)
    DEBUG_FLAGS   = -g -O0 -traceback

    ifeq ($(OPENMP_MODE),ON)
        OPENMP    = -qopenmp
    else
        OPENMP    = -qopenmp-stubs
    endif
    ifeq ($(OPENACC_MODE),ON)
        OPENACC   =
    else
        OPENACC   =
    endif

    # Fortran-specific flags
    OPT_FFLAGS    =
    DEBUG_FFLAGS  = -check all,noarg_temp_created -fpe0 -gen-interfaces -warn interfaces

    F77FLAGS      = -fpp -real-size 64 -integer-size 32
    F90FLAGS      = -fpp -real-size 64 -integer-size 32

    # Linker flags
    OPT_LDFLAGS   =
    DEBUG_LDFLAGS =

else ifeq ($(PE_ENV),PGI)

    ifneq ($(FC),ftn)
        FC        = pgfortran
        LDR       = pgfortran

        ARCHOPT   =
    endif
    INLINE    = -Mipa=fast,inline,safe

    # generic flags
    OPT_FLAGS     = -g -gopt -fast $(ARCHOPT) $(INLINE)
    DEBUG_FLAGS   = -g -gopt -O0 -traceback

    ifeq ($(OPENMP_MODE),ON)
        OPENMP    = -mp
    else
        OPENMP    = -mp -Mnoopenmp
    endif
    ifeq ($(OPENACC_MODE),ON)
        OPENACC   = -acc -ta=tesla:ptxinfo -Minfo=accel
    else
        OPENACC   =
    endif

    # Fortran-specific flags
    OPT_FFLAGS    =
    DEBUG_FFLAGS  = -Ktrap=fp -Mbounds -Mchkptr -Mdclchk

    F77FLAGS      = -Mpreprocess -r8 -i4 -Mfixed
    F90FLAGS      = -Mpreprocess -r8 -i4

    # Linker flags
    OPT_LDFLAGS   = -pgc++libs
    DEBUG_LDFLAGS = -pgc++libs

else ifneq ($(filter NVIDIA NVHPC,$(PE_ENV)),)

    ifneq ($(FC),ftn)
        FC        = nvfortran
        LDR       = nvfortran

        ARCHOPT   = -tp=pwr9
    endif
    INLINE    =# -Mipa=fast,inline,safe

    # generic flags
    OPT_FLAGS     = -g -gopt -O2 $(ARCHOPT) $(INLINE)
    DEBUG_FLAGS   = -g -gopt -O0 -traceback

    ifeq ($(OPENMP_MODE),ON)
        OPENMP    = -mp=multicore
    else
        OPENMP    =# -mp=multicore -Mnoopenmp
    endif
    ifeq ($(OPENACC_MODE),ON)
        OPENACC   = -acc -gpu=ptxinfo -Minfo=accel
    else
        OPENACC   =
    endif

    # Fortran-specific flags
    OPT_FFLAGS    =
    DEBUG_FFLAGS  = -Ktrap=fp -Mbounds -Mchkptr -Mdclchk

    F77FLAGS      = -Mpreprocess -r8 -i4 -Mfixed
    F90FLAGS      = -Mpreprocess -r8 -i4

    # Linker flags
    OPT_LDFLAGS   = -pgc++libs
    DEBUG_LDFLAGS = -pgc++libs

else ifeq ($(PE_ENV),GNU)

    ifneq ($(FC),ftn)
        FC        = gfortran
        LDR       = gfortran

        ARCHOPT   = -march=native
    endif

    # generic flags
    OPT_FLAGS     = -g -Ofast -funroll-loops -fprefetch-loop-arrays $(ARCHOPT) $(INLINE)
    DEBUG_FLAGS   = -g -Og -ggdb -ftrapv -fexceptions -Wall -Wextra \
                    -Wno-unused-variable -Wno-unused-parameter

    ifeq ($(OPENMP_MODE),ON)
        OPENMP    = -fopenmp
    else
        OPENMP    = -lgomp
    endif
    ifeq ($(OPENACC_MODE),ON)
        OPENACC   = -fopenacc
    else
        OPENACC   =
    endif

    # Fortran-specific flags
    OPT_FFLAGS    =
    DEBUG_FFLAGS  = -fcheck=bounds,do,mem,pointer -ffpe-trap=invalid,zero,overflow -fbacktrace \
                    -Wno-unused-dummy-argument -Wno-unused-label -Wno-maybe-uninitialized

    F77FLAGS      = -cpp -fdefault-real-8 -fdefault-double-8 -fimplicit-none -fallow-argument-mismatch -Wno-compare-reals
    F90FLAGS      = -cpp -fdefault-real-8 -fdefault-double-8 -fimplicit-none -fallow-argument-mismatch -ffree-line-length-none

    # Linker flags
    OPT_LDFLAGS   =
    DEBUG_LDFLAGS =

else ifeq ($(PE_ENV),LLVM)

    ifneq ($(FC),ftn)
        FC        = flang
        LDR       = flang
        ARCHOPT   = -march=native
    endif

    # generic flags
    OPT_FLAGS     = -g -O3 -funroll-loops $(ARCHOPT) $(INLINE)
    DEBUG_FLAGS   = -g -O0


    ifeq ($(OPENMP_MODE),ON)
        OPENMP    = -fopenmp
    else
        OPENMP    =# -lgomp
    endif
    ifeq ($(OPENACC_MODE),ON)
        OPENACC   =# -fopenacc
    else
        OPENACC   =
    endif

    # Fortran-specific flags
    OPT_FFLAGS    =
    DEBUG_FFLAGS  =

    F77FLAGS      = -cpp -fdefault-real-8 -fdefault-double-8 -fimplicit-none -Wno-folding-value-checks
    F90FLAGS      = -cpp -fdefault-real-8 -fdefault-double-8 -fimplicit-none -Wno-folding-value-checks

    # Linker flags
    OPT_LDFLAGS   =
    DEBUG_LDFLAGS =

else ifneq ($(filter CCE CRAY,$(PE_ENV)),)

    INLINE_DB     = $(BUILD_DIR)/xnet_inline
    INLINE        = -h wp -h pl=$(INLINE_DB)

    # generic flags
    OPT_FLAGS     = -O2 -g
    DEBUG_FLAGS   = -O0 -eD

    ifeq ($(OPENMP_MODE),ON)
        OPENMP    = -fopenmp
    else
        OPENMP    =
    endif
    ifeq ($(OPENACC_MODE),ON)
        OPENACC   = -h acc
    else
        OPENACC   = -h noacc
    endif
    ifeq ($(OPENMP_OL_MODE),ON)
        OPENMP_OL = -fopenmp
    else
        OPENMP_OL =
    endif

    # Fortran-specific flags
    OPT_FFLAGS    =
    DEBUG_FFLAGS  =

    F77FLAGS      = -eZ -s real64 -s integer32
    F90FLAGS      = -eZ -s real64 -s integer32

    # Linker flags
    OPT_LDFLAGS   =
    DEBUG_LDFLAGS =

else ifeq ($(PE_ENV),XL)

    ifneq ($(FC),ftn)
        FC        = xlf2008_r
        LDR       = xlf90_r

        ARCHOPT   = -qarch=pwr9 -qtune=pwr9
    endif

    # generic flags
    OPT_FLAGS     = -g -O3 -w $(ARCHOPT) $(INLINE)
    DEBUG_FLAGS   = -g -O0 -qnosmp -qstrict=all -qfloat=rngchk -qcheck=all:nounset \
                    -qflttrap=enable:invalid:nanq:overflow:zerodivide -qsigtrap=xl__trcedump

    ifeq ($(OPENMP_MODE),ON)
        OPENMP    = -qsmp=omp:noauto
    else
        OPENMP    =
    endif
    ifeq ($(OPENACC_MODE),ON)
        OPENACC   =
    else
        OPENACC   =
    endif

    # Fortran-specific flags
    OPT_FFLAGS    =
    DEBUG_FFLAGS  = -qflag=i:w

    F77FLAGS      = -qpreprocess -qintsize=4 -qrealsize=8 -qzerosize -qport=c_loc -qundef -qsuppress=cmpmsg -qfixed
    F90FLAGS      = -qpreprocess -qintsize=4 -qrealsize=8 -qzerosize -qport=c_loc -qundef -qsuppress=cmpmsg

    # Linker flags
    OPT_LDFLAGS   =
    DEBUG_LDFLAGS =

else

    $(error PE_ENV = \"$(PE_ENV)\" not supported )

endif

## Override compiler for MPI
ifeq ($(MPI_MODE),ON)
    FC  = $(FC_MPI)
    LDR = $(LDR_MPI)
endif

#-------------------------------------------------------------------------------
# Library definitions and compile/link flags
#-------------------------------------------------------------------------------

## Intel Math Kernel Library (MKL)
ifeq ($(UNAME_S),Darwin)
    INTEL_PATH ?= /opt/intel/compilers_and_libraries/mac
    MKL_OS = mac
else
    INTEL_PATH ?= /opt/intel/compilers_and_libraries/linux
    MKL_OS = lnx
endif
MKLROOT    ?= $(INTEL_PATH)/mkl
MKL_LINK_TOOL := $(firstword $(wildcard ${MKLROOT}/tools/mkl_link_tool ${MKLROOT}/bin/mkl_link_tool))
ifneq ("$(MKL_LINK_TOOL)","")
    ifeq ($(PE_ENV),INTEL)
        MKL_INC  ?= $(shell ${MKL_LINK_TOOL} -opts --quiet --parallel=no --compiler=intel_f --os=${MKL_OS} --linking=static)
        MKL_LIBS ?= $(shell ${MKL_LINK_TOOL} -libs --quiet --parallel=no --compiler=intel_f --os=${MKL_OS} --linking=static)
    else ifeq ($(PE_ENV),PGI)
        MKL_INC  ?= $(shell ${MKL_LINK_TOOL} -opts --quiet --parallel=no --compiler=pgi_f --os=${MKL_OS} --linking=static)
        MKL_LIBS ?= $(shell ${MKL_LINK_TOOL} -libs --quiet --parallel=no --compiler=pgi_f --os=${MKL_OS} --linking=static)
    else ifeq ($(PE_ENV),GNU)
        MKL_INC  ?= $(shell ${MKL_LINK_TOOL} -opts --quiet --parallel=no --compiler=gnu_f --os=${MKL_OS} --linking=static)
        MKL_LIBS ?= $(shell ${MKL_LINK_TOOL} -libs --quiet --parallel=no --compiler=gnu_f --os=${MKL_OS} --linking=static)
    else ifeq ($(PE_ENV),CRAY)
        MKL_INC  ?= $(shell ${MKL_LINK_TOOL} -opts --quiet --parallel=no --compiler=gnu_f --os=${MKL_OS} --linking=static)
        MKL_LIBS ?= $(shell ${MKL_LINK_TOOL} -libs --quiet --parallel=no --compiler=gnu_f --os=${MKL_OS} --linking=static)
    endif
endif

## Mac Accelerate Framework
ACCEL_INC      = -framework Accelerate
ACCEL_LIBS     = -framework Accelerate

## ATLAS
ATLAS_DIR     ?= /usr/local/atlas
ATLAS_INC      = -I$(ATLAS_DIR)/include
ATLAS_LIBDIR   = -L$(ATLAS_DIR)/lib
ATLAS_LIBS     = -llapack -lf77blas -lcblas -latlas

## NETLIB
NETLIB_DIR    ?= $(ROOT_DIR)/tools/LAPACK
BLAS_LVL1_SRC  = dcopy.f ddot.f dlamch.f dnrm2.f dscal.f dswap.f idamax.f lsame.f xerbla.f
BLAS_LVL2_SRC  = daxpy.f dger.f dgemv.f dtrmv.f dtrsv.f
BLAS_LVL3_SRC  = dgemm.f dtrmm.f dtrsm.f
LAPACK_UTL_SRC = ieeeck.f iparmq.f ilaenv.f iladlc.f iladlr.f
LAPACK_AUX_SRC = dgetrf2.f dlaswp.f dlapy2.f \
                 dlaisnan.f dlarf.f dlarfg.f \
                 dgelq2.f dgeqr2.f disnan.f dlarfb.f dlarft.f dlassq.f dorm2r.f dorml2.f \
                 dgelqf.f dgeqrf.f dlabad.f dlange.f dlascl.f dlaset.f dormlq.f dormqr.f dtrtrs.f
NETLIB_SRC     = $(addprefix $(NETLIB_DIR)/, \
		 $(BLAS_LVL1_SRC) $(BLAS_LVL2_SRC) $(BLAS_LVL3_SRC) \
		 $(LAPACK_UTL_SRC) $(LAPACK_AUX_SRC) \
		 dgels.f dgetrf.f dgetrs.f dgesv.f)

## ESSL
ESSL_DIR    ?= $(OLCF_ESSL_ROOT)
ESSL_INC     = -I$(ESSL_DIR)/include
ESSL_LIBDIR  = -L$(ESSL_DIR)/lib64
ESSL_LIBS    = -lessl

## PGI
PGIBLAS_LIBS = -llapack -lblas

LAPACK_INC    = $($(LAPACK_VER)_INC)
LAPACK_LIBDIR = $($(LAPACK_VER)_LIBDIR)
LAPACK_LIBS   = $($(LAPACK_VER)_LIBS)
LAPACK_SRC    = $($(LAPACK_VER)_SRC)

## MA48
MA48_DIR      ?= .
MA48_SRC       = $(MA48_DIR)/MA48.f

## MA41
MA41_DIR      ?= .
MA41_SRC       = $(MA41_DIR)/MA41.f

SOLVER_INC     = $($(MATRIX_SOLVER)_INC)
SOLVER_LIBDIR  = $($(MATRIX_SOLVER)_LIBDIR)
SOLVER_LIBS    = $($(MATRIX_SOLVER)_LIBS)

## Define compiler flags
FLAGS     = $($(CMODE)_FLAGS) $(EXTRA_FLAGS)
FFLAGS   += $(FLAGS) $($(CMODE)_FFLAGS) $(OPENMP)
LDFLAGS  += $(FLAGS) $($(CMODE)_LDFLAGS) $(OPENMP)
